### ISSUE TITLE
Link werkt niet meer

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/remote-assessment-aid#79]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/a6157d236570662ef030f814aeb9dc8e0489e667/content/snippets/observation/obs_tips_peerfeedback.md?plain=1#L1

de volgende link werkt niet meer, het bestand is waarschijnlijk verwijderd:
https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf

Is dit misschien de betreffende factsheet?
https://www.inholland.nl/onderzoek/publicaties/handreiking-voor-het-scripten-van-peerreview/

**Comment by ShKlinkenberg** [comment]
inderdaad. Heb de nieuwe link toegevoegd
