### ISSUE TITLE
Referenties worden niet getoond 6 en spatie verwijderen tussen verwijzing en link

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/remote-assessment-aid#82]
Op de pagina van de toetsvorm Open-boektentamen en take-hometentamen zijn er ook een aantal referenties die niet worden getoond, waaronder: [@heijne2011directing] ,[@bengtsson2019take] en [@van2017toetsen]

Ik kan deze pagina zelf echter ook niet in Github vinden.

Op deze pagina moet op twee plekken ook nog een spatie worden verwijderd tussen
[Soeting en Haykens (z.d.)] en de link: (https://husite.nl/toetsing-nieuw/wp-content/uploads/sites/299/2020/02/Cesuurbepaling.pdf)

**Comment by ShKlinkenberg** [comment]
bestanden waren md en niet Rmd daarom konden de referenties niet gerendered worden.
