### ISSUE TITLE
Referentie: link naar (online) pdf ontbreekt

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/remote-assessment-aid#83]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/a6157d236570662ef030f814aeb9dc8e0489e667/content/medium/knowledge/methods/oral_exams.Rmd#L10

Hier wordt de referentie (Van Berkel, Bax, & Joosten-ten-Brinke, 2017) wel juist weergegeven, alleen ontbreekt hier de link naar de pdf die online staat (op andere plekken werkt deze link wel).

**Comment by ShKlinkenberg** [comment]
@RRochelleH de referentie is er als text ingezet en niet als @ referentie.

**Comment by ShKlinkenberg** [comment]
ik heb het al opgelost
