### ISSUE TITLE
Subtitel Digitale Toetsen: 'take-home tentamen, openboektoets' nog verwijderen

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/remote-assessment-aid#93]
take-home tentamen, openboektoets --> dit moet nog worden verwijderd in de subtitel van Digitale Toetsen

**Comment by ShKlinkenberg** [comment]
Ik denk dat dit al gedaan is. Tenminste als je deze bedoeld.

https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/methods/digital_assessment/
