### ISSUE TITLE
Presentaties wordt nu 2x weergegeven

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/remote-assessment-aid#94]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/a6157d236570662ef030f814aeb9dc8e0489e667/content/large/application/methods/presentation.Rmd#L2

Dit is de juiste beschrijving van de geadviseerde toetsvorm Presentaties, bij groepsgrootte groot op niveau van toepassing. Er wordt hiernaast echter ook nog de oude beschrijving van Presentaties weergegeven ('Presentaties' staat er dubbel in bij deze geadviseerde toetsvormen). De oude versie moet nog worden verwijderd.

**Comment by ShKlinkenberg** [comment]
@EdwinBuijs welke van de twee moet er weg? Die met de bullets?

@RRochelleH bij 

https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/large/application/

zou jij de oude weg willen halen?
